wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: adam
weight_init:
  value: xavier
