wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: adam
weight_init:
  value: xavier
