wandb_version: 1

method:
  desc: null
  value: bayes
name:
  desc: null
  value: complete-hyperparameter-sweep
metric:
  desc: null
  value:
    name: validation accuracy
    goal: maximize
parameters:
  desc: null
  value:
    epochs:
      values:
      - 5
      - 10
    num_layers:
      values:
      - 3
      - 4
    hidden_size:
      values:
      - 32
      - 64
      - 128
    learning_rate:
      values:
      - 0.001
      - 0.0001
    optimizer:
      values:
      - sgd
      - momentum
      - nesterov
      - rmsprop
      - adam
      - nadam
    batch_size:
      values:
      - 16
      - 32
      - 64
    weight_init:
      values:
      - random
      - xavier
    activation:
      values:
      - sigmoid
      - tanh
      - relu
    loss:
      values:
      - cross_entropy
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710682342.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 24
      - 37
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: cross_entropy
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: nadam
weight_init:
  desc: null
  value: xavier
